const PARSE_DATA_ACTIONS = {
  SET_PERIOD_DATA: "SET_PERIOD_DATA",
  SET_DATE_MODE: "SET_DATE_MODE",
  SET_DATE_PERIOD: "SET_DATE_PERIOD",
  SET_RESOURCE: "SET_RESOURCE",
};

export default PARSE_DATA_ACTIONS;
